version: "3.8"

services:
  api:
    container_name: "api"
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_API_CPUS:-0}"
          memory: "${DOCKER_API_MEMORY:-0}"
    build: 
      context: "."
    env_file:
     - ".env"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    ports:
      - "${DOCKER_API_PORT_FORWARD:-127.0.0.1:3000}:${PORT:-3000}"
    volumes:
      - ".:/app"

  db:
    container_name: "db"
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_POSTGRES_CPUS:-0}"
          memory: "${DOCKER_POSTGRES_MEMORY:-0}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    image: "postgres:15.1-bullseye"
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"

volumes:
  postgres: {}
